version: 2
updates:
  # Maintain dependencies for npm packages
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'security'
    groups:
      angular:
        patterns:
          - '@angular*'
          - 'typescript'
          - 'zone.js'
          - 'rxjs'
      dependencies:
        patterns:
          - '*'

  # Maintain dependencies for GitHub Actions workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    labels:
      - 'ci'
      - 'dependencies'
    groups:
      actions:
        patterns:
          - '*'
